### ISSUE TITLE
Multi-threading Support

### ISSUE THREAD

**Issue by harsimranb** [knuppe/SharpNL#26]
I am trying to classify a bunch of items using Parallel.ForEach.  It seems that SharpNL is not working well with multithreading.  I am getting the following errors:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpNL.Utility.Cache.Clear() in c:\GitHub\SharpNL\src\SharpNL\Utility\Cache.cs:line 93
   at SharpNL.Utility.FeatureGen.CachedFeatureGenerator.CreateFeatures(List`1 features, String[] tokens, Int32 index, String[] previousOutcomes) in c:\GitHub\SharpNL\src\SharpNL\Utility\FeatureGen\CachedFeatureGenerator.cs:line 86
   at SharpNL.NameFind.DefaultNameContextGenerator.GetContext(Int32 index, String[] tokens, String[] preds, Object[] additionalContext) in c:\GitHub\SharpNL\src\SharpNL\NameFind\DefaultNameContextGenerator.cs:line 83
   at SharpNL.ML.BeamSearch`1.BestSequences(Int32 numSequences, T[] sequence, Object[] additionalContext, Double minSequenceScore, IBeamSearchContextGenerator`1 beamSearch, ISequenceValidator`1 validator) in c:\GitHub\SharpNL\src\SharpNL\ML\BeamSearch.cs:line 140
   at SharpNL.ML.BeamSearch`1.BestSequences(Int32 numSequences, T[] sequence, Object[] additionalContext, IBeamSearchContextGenerator`1 beamSearch, ISequenceValidator`1 validator) in c:\GitHub\SharpNL\src\SharpNL\ML\BeamSearch.cs:line 108
   at SharpNL.ML.BeamSearch`1.BestSequence(T[] sequence, Object[] additionalContext, IBeamSearchContextGenerator`1 beamSearch, ISequenceValidator`1 validator) in c:\GitHub\SharpNL\src\SharpNL\ML\BeamSearch.cs:line 84
   at SharpNL.NameFind.NameFinderME.Find(String[] tokens, String[][] additionalContext) in c:\GitHub\SharpNL\src\SharpNL\NameFind\NameFinderME.cs:line 221
```

I will try to look into this more when I get time.  I just wanted to bring this to your attention.

**Comment by knuppe** [comment]
Take a look at the following test, 100 threads with no problem. :sunglasses: 
[NameFinderMultithreadingTest.cs](https://github.com/knuppe/SharpNL/blob/development/src/SharpNL.Tests/NameFind/NameFinderMultithreadingTest.cs#L43)

**Comment by harsimranb** [comment]
Nice!  Unfortunately, loading an instance of the model per thread is very expensive.  I needed to make it fast.  I made some changes in the code to allow multi-threaded support.  Now, I have true multi-threaded support for SharpNL, where I load the models once into memory as static members and share them across multiple threads.  It's very nice!  I can submit a pull request if you're interested.

**Comment by knuppe** [comment]
There is no need to instantiate one model per thread, you can share the same model instance across the threads. This is the design of the original library and it works very well.
